# Generated by Django 2.2.14 on 2020-08-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='full_record_url',
            field=models.URLField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
