# Generated by Django 2.2.14 on 2020-07-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='form',
            field=models.CharField(choices=[('digitized', 'Digitized'), ('born_digital', 'Born Digital')], default='digitized', max_length=16),
        ),
        migrations.AddField(
            model_name='text',
            name='identifer',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='title',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='text',
            name='type',
            field=models.CharField(choices=[('article', 'Article'), ('book_excerpt', 'Book (excerpt)'), ('book_whole', 'Book (whole)'), ('other', 'Other')], default='article', max_length=16),
        ),
    ]
