# Generated by Django 2.2.14 on 2020-08-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
