# Generated by Django 2.2.14 on 2020-08-04 19:04

from django.db import migrations, models
import uploads.validators


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='upload',
            name='barcode',
            field=models.CharField(blank=True, max_length=512, null=True, validators=[uploads.validators.validate_barcode]),
        ),
    ]
