# Generated by Django 2.2.14 on 2020-08-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processing_status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
