# Generated by Django 2.2.14 on 2020-08-03 19:06

from django.db import migrations, models
import django.utils.timezone
import uploads.models
import uploads.validators


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotrack',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='title',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='upload',
            field=models.FileField(help_text='mp3 format only', max_length=1024, upload_to=uploads.models.audiotrack_upload_path, validators=[uploads.validators.validate_audio]),
        ),
    ]
