# Generated by Django 2.2.14 on 2020-07-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
