# Generated by Django 2.2.14 on 2020-08-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_upload_full_record_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='full_record_url',
            field=models.URLField(blank=True, help_text='E.g. Libguides Reserves system record', max_length=1024, null=True),
        ),
    ]
