# Generated by Django 2.2.14 on 2020-08-11 19:52

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_auto_20200804_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiotrack',
            options={'ordering': ['track_order']},
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='track_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='album',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.AudioAlbum'),
        ),
    ]
