# Generated by Django 2.2.14 on 2020-08-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_auto_20200827_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text_type',
            field=models.CharField(choices=[('article', 'Article'), ('book_excerpt', 'Book (excerpt)'), ('book_whole', 'Book (whole)'), ('other', 'Other')], help_text='Text type cannot be changed after saving.', max_length=16),
        ),
    ]
