# Generated by Django 2.2.14 on 2020-08-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_auto_20200730_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='type',
            new_name='text_type',
        ),
    ]
