# Generated by Django 2.2.14 on 2020-09-10 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20200827_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'permissions': [('view_inventory', 'Can view non-staff inventory of materials (for faculty)')]},
        ),
    ]
