# Generated by Django 2.2.14 on 2020-08-03 14:53

from django.db import migrations, models
import django.db.models.deletion
import uploads.validators


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20200803_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAlbum',
            fields=[
                ('upload_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='uploads.Upload')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('uploads.upload',),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_type',
            field=models.CharField(choices=[('article', 'Article'), ('book_excerpt', 'Book (excerpt)'), ('book_whole', 'Book (whole)'), ('other', 'Other')], default='article', help_text='Text type cannot be changed after saving.', max_length=16),
        ),
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('upload_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='uploads.Upload')),
                ('upload', models.FileField(help_text='mp3 format only', max_length=1024, upload_to='av/audio/', validators=[uploads.validators.validate_audio])),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.AudioAlbum')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('uploads.upload',),
        ),
    ]
