# Generated by Django 2.2.14 on 2020-07-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20200727_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='identifer',
            new_name='identifier',
        ),
    ]
