# Generated by Django 2.2.14 on 2020-08-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20200811_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='identifier',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
