# Generated by Django 2.2.14 on 2020-07-27 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_auto_20200727_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('upload_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='uploads.Upload')),
                ('upload', models.FileField(max_length=512, upload_to='av/video/')),
            ],
            bases=('uploads.upload',),
        ),
    ]
