# Generated by Django 2.2.14 on 2020-08-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_upload_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
