# Generated by Django 2.2.14 on 2020-08-31 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_auto_20200824_1513'),
        ('uploads', '0003_auto_20200827_1507'),
    ]

    operations = [
    ]
