# Generated by Django 2.2.14 on 2020-07-27 17:50

from django.db import migrations, models
import django.db.models.deletion
import uploads.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('upload_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='uploads.Upload')),
                ('upload', models.FileField(max_length=1024, upload_to='av/audio/')),
            ],
            bases=('uploads.upload',),
        ),
        migrations.AlterField(
            model_name='text',
            name='upload',
            field=models.FileField(max_length=1024, upload_to=uploads.models.text_upload_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='upload',
            field=models.FileField(max_length=1024, upload_to='av/video/'),
        ),
    ]
