# Generated by Django 2.2.14 on 2020-09-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_merge_20200831_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='lock_panopto_session_id',
            field=models.BooleanField(default=False),
        ),
    ]
