# Generated by Django 2.2.14 on 2020-07-27 20:35

from django.db import migrations, models
import uploads.models
import uploads.validators


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_auto_20200727_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='upload',
            field=models.FileField(help_text='mp3 format only', max_length=1024, upload_to='av/audio/', validators=[uploads.validators.validate_audio]),
        ),
        migrations.AlterField(
            model_name='text',
            name='upload',
            field=models.FileField(help_text='pdf format only', max_length=1024, upload_to=uploads.models.text_upload_path, validators=[uploads.validators.validate_text]),
        ),
        migrations.AlterField(
            model_name='video',
            name='upload',
            field=models.FileField(help_text='mp4 format only', max_length=1024, upload_to='av/video/', validators=[uploads.validators.validate_video]),
        ),
    ]
