# Generated by Django 2.2.14 on 2020-10-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0007_video_lock_panopto_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
