# Generated by Django 2.2.14 on 2020-11-16 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_auto_20200910_1419'),
        ('uploads', '0008_auto_20201019_1003'),
    ]

    operations = [
    ]
