# Generated by Django 2.2.14 on 2020-08-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0008_videovtttrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='videovtttrack',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('zh', 'Chinese')], default='en', max_length=2),
            preserve_default=False,
        ),
    ]
