# Generated by Django 2.2.14 on 2020-08-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0009_videovtttrack_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='videovtttrack',
            name='name',
            field=models.CharField(blank=True, help_text="Optional - Overrides the description given by the type and language. You shouldn't use this unless you know what you are doing.", max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='videovtttrack',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('zh', 'Chinese')], default='en', max_length=2),
        ),
    ]
