# Generated by Django 2.2.14 on 2021-01-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0010_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='lock_panopto_session_id',
            field=models.BooleanField(default=False),
        ),
    ]
