# Generated by Django 2.2.14 on 2020-08-13 17:13

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0010_auto_20200813_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videovtttrack',
            name='name',
            field=models.CharField(blank=True, help_text="Optional - Overrides the name in the user interface set by the type and language. Don't use this unless you know what you are doing.", max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='videovtttrack',
            name='video',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.Video'),
        ),
    ]
