# Generated by Django 2.2.14 on 2021-11-05 17:47

from django.db import migrations, models
import uploads.validators


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0011_audio_lock_panopto_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='upload',
            field=models.FileField(help_text='mp3 or wav format only', max_length=1024, upload_to='av/audio/', validators=[uploads.validators.validate_audio]),
        ),
        migrations.AlterField(
            model_name='videovtttrack',
            name='language',
            field=models.CharField(choices=[('English_USA', 'English (United States)'), ('English_GBR', 'English (United Kingdom)'), ('English_AUS', 'English (Australia)'), ('Spanish_MEX', 'Spanish (Mexico)'), ('Spanish_ESP', 'Spanish (Spain)'), ('Chinese_Simplified', 'Chinese (Simplified)'), ('Chinese_Traditional', 'Chinese (Traditional)'), ('Danish', 'Danish'), ('Dutch', 'Dutch'), ('Finnish', 'Finnish'), ('French', 'French'), ('German', 'German'), ('Hungarian', 'Hungarian'), ('Italian', 'Italian'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Norwegian', 'Norwegian'), ('Polish', 'Polish'), ('Portuguese', 'Portuguese'), ('Russian', 'Russian'), ('Swedish', 'Swedish'), ('Thai', 'Thai')], default='English_USA', max_length=20),
        ),
        migrations.AlterField(
            model_name='videovtttrack',
            name='type',
            field=models.CharField(choices=[('subtitles', 'Subtitles (for language translations)'), ('captions', 'Captions (for Deaf and hard-of-hearing users)'), ('descriptions', 'Descriptions (for vision impairment)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='videovtttrack',
            name='upload',
            field=models.FileField(help_text='vtt format only', max_length=1024, upload_to='av/vtt/'),
        ),
        migrations.RenameModel(
            'VideoVttTrack', 'VttTrack'
        ),
    ]
