CREATE TABLE `uploads_audioplaylist` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `title` varchar(512) NOT NULL, `panopto_playlist_id` varchar(256) NULL);
CREATE TABLE `uploads_audioplaylistlink` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `playlist_order` integer UNSIGNED NOT NULL CHECK (`playlist_order` >= 0));
CREATE TABLE `uploads_videoplaylist` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `title` varchar(512) NOT NULL, `panopto_playlist_id` varchar(256) NULL);
CREATE TABLE `uploads_videoplaylistlink` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `playlist_order` integer UNSIGNED NOT NULL CHECK (`playlist_order` >= 0), `av_id` char(32) NOT NULL, `playlist_id` integer NOT NULL, `polymorphic_ctype_id` integer NULL);
CREATE TABLE `uploads_vtttrack` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `upload` varchar(1024) NOT NULL, `type` varchar(20) NOT NULL, `language` varchar(20) NOT NULL, `label` varchar(16) NULL, `modified` datetime(6) NOT NULL, `created` datetime(6) NOT NULL, `vtt_order` integer UNSIGNED NOT NULL CHECK (`vtt_order` >= 0), `video_id` char(32) NOT NULL);
ALTER TABLE `uploads_audiotrack` DROP FOREIGN KEY `uploads_audiotrack_album_id_2d3ed3f7_fk_uploads_a`;
ALTER TABLE `uploads_audiotrack` DROP COLUMN `album_id`;
ALTER TABLE `uploads_videovtttrack` DROP FOREIGN KEY `uploads_videovtttrac_video_id_86d27e87_fk_uploads_v`;
ALTER TABLE `uploads_videovtttrack` DROP COLUMN `video_id`;
DROP TABLE `uploads_audioalbum` CASCADE;
DROP TABLE `uploads_audiotrack` CASCADE;
DROP TABLE `uploads_videovtttrack` CASCADE;
ALTER TABLE `uploads_videoplaylist` ADD COLUMN `polymorphic_ctype_id` integer NULL , ADD CONSTRAINT `uploads_videoplaylis_polymorphic_ctype_id_6d18dc8c_fk_django_co` FOREIGN KEY (`polymorphic_ctype_id`) REFERENCES `django_content_type`(`id`);
ALTER TABLE `uploads_audioplaylistlink` ADD COLUMN `av_id` char(32) NOT NULL COLLATE utf8mb3_bin , ADD CONSTRAINT `uploads_audioplaylis_av_id_05e57fa5_fk_uploads_a` FOREIGN KEY (`av_id`) REFERENCES `uploads_audio`(`upload_ptr_id`);
ALTER TABLE `uploads_audioplaylistlink` ADD COLUMN `playlist_id` integer NOT NULL , ADD CONSTRAINT `uploads_audioplaylis_playlist_id_a8964622_fk_uploads_a` FOREIGN KEY (`playlist_id`) REFERENCES `uploads_audioplaylist`(`id`);
ALTER TABLE `uploads_audioplaylistlink` ADD COLUMN `polymorphic_ctype_id` integer NULL , ADD CONSTRAINT `uploads_audioplaylis_polymorphic_ctype_id_9d19272a_fk_django_co` FOREIGN KEY (`polymorphic_ctype_id`) REFERENCES `django_content_type`(`id`);
ALTER TABLE `uploads_audioplaylist` ADD COLUMN `polymorphic_ctype_id` integer NULL , ADD CONSTRAINT `uploads_audioplaylis_polymorphic_ctype_id_6d9d3318_fk_django_co` FOREIGN KEY (`polymorphic_ctype_id`) REFERENCES `django_content_type`(`id`);
ALTER TABLE `uploads_audioplaylistlink` ADD CONSTRAINT `uploads_audioplaylistlink_av_id_playlist_id_362c8e03_uniq` UNIQUE (`av_id`, `playlist_id`);
ALTER TABLE `uploads_videoplaylistlink` ADD CONSTRAINT `uploads_videoplaylistlink_av_id_playlist_id_6f6eb475_uniq` UNIQUE (`av_id`, `playlist_id`);
ALTER TABLE `uploads_videoplaylistlink` ADD CONSTRAINT `uploads_videoplaylis_av_id_4153a169_fk_uploads_v` FOREIGN KEY (`av_id`) REFERENCES `uploads_video` (`upload_ptr_id`);
ALTER TABLE `uploads_videoplaylistlink` ADD CONSTRAINT `uploads_videoplaylis_playlist_id_98168d6a_fk_uploads_v` FOREIGN KEY (`playlist_id`) REFERENCES `uploads_videoplaylist` (`id`);
ALTER TABLE `uploads_videoplaylistlink` ADD CONSTRAINT `uploads_videoplaylis_polymorphic_ctype_id_d31ee4a4_fk_django_co` FOREIGN KEY (`polymorphic_ctype_id`) REFERENCES `django_content_type` (`id`);
ALTER TABLE `uploads_vtttrack` ADD CONSTRAINT `uploads_vtttrack_video_id_10947d58_fk_uploads_v` FOREIGN KEY (`video_id`) REFERENCES `uploads_video` (`upload_ptr_id`);
CREATE INDEX `uploads_vtttrack_vtt_order_40964e49` ON `uploads_vtttrack` (`vtt_order`);
