# Generated by Django 2.2.14 on 2020-08-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0011_auto_20200813_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videovtttrack',
            options={'ordering': ['vtt_order']},
        ),
        migrations.AddField(
            model_name='videovtttrack',
            name='vtt_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
