# Generated by Django 3.2.9 on 2021-12-07 19:35

from django.db import migrations, models
import django.db.models.deletion
import uploads.validators


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('uploads', '0011_audio_lock_panopto_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('panopto_playlist_id', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AudioPlaylistLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['playlist_order'],
            },
        ),
        migrations.CreateModel(
            name='VideoPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('panopto_playlist_id', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoPlaylistLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_order', models.PositiveIntegerField(default=0)),
                ('av', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.video')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.videoplaylist')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_uploads.videoplaylistlink_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['playlist_order'],
                'unique_together': {('av', 'playlist')},
            },
        ),
        migrations.CreateModel(
            name='VttTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(help_text='vtt format only', max_length=1024, upload_to='av/vtt/', validators=[uploads.validators.validate_captions])),
                ('type', models.CharField(choices=[('subtitles', 'Subtitles (for language translations)'), ('captions', 'Captions (for Deaf and hard-of-hearing users)'), ('descriptions', 'Descriptions (for vision impairment)')], max_length=20)),
                ('language', models.CharField(choices=[('English_USA', 'English (United States)'), ('English_GBR', 'English (United Kingdom)'), ('English_AUS', 'English (Australia)'), ('Spanish_MEX', 'Spanish (Mexico)'), ('Spanish_ESP', 'Spanish (Spain)'), ('Chinese_Simplified', 'Chinese (Simplified)'), ('Chinese_Traditional', 'Chinese (Traditional)'), ('Danish', 'Danish'), ('Dutch', 'Dutch'), ('Finnish', 'Finnish'), ('French', 'French'), ('German', 'German'), ('Hungarian', 'Hungarian'), ('Italian', 'Italian'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Norwegian', 'Norwegian'), ('Polish', 'Polish'), ('Portuguese', 'Portuguese'), ('Russian', 'Russian'), ('Swedish', 'Swedish'), ('Thai', 'Thai')], default='English_USA', max_length=20)),
                ('label', models.CharField(blank=True, help_text="Optional - Users see this. Overrides the name in the user interface generated from the Type and Language fields. Don't use this unless you know what you are doing.", max_length=16, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('vtt_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.video')),
            ],
            options={
                'ordering': ['vtt_order'],
            },
        ),
        migrations.RemoveField(
            model_name='audiotrack',
            name='album',
        ),
        migrations.RemoveField(
            model_name='videovtttrack',
            name='video',
        ),
        migrations.AlterModelOptions(
            name='upload',
            options={'permissions': [('view_inventory', 'Can view non-staff inventory of materials (for faculty)')], 'verbose_name_plural': 'Uploads (all types)'},
        ),
        migrations.AlterField(
            model_name='audio',
            name='upload',
            field=models.FileField(help_text='mp3, m4a or wav', max_length=1024, upload_to='av/audio/', validators=[uploads.validators.validate_audio]),
        ),
        migrations.DeleteModel(
            name='AudioAlbum',
        ),
        migrations.DeleteModel(
            name='AudioTrack',
        ),
        migrations.DeleteModel(
            name='VideoVttTrack',
        ),
        migrations.AddField(
            model_name='videoplaylist',
            name='av',
            field=models.ManyToManyField(through='uploads.VideoPlaylistLink', to='uploads.Video'),
        ),
        migrations.AddField(
            model_name='videoplaylist',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_uploads.videoplaylist_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='audioplaylistlink',
            name='av',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.audio'),
        ),
        migrations.AddField(
            model_name='audioplaylistlink',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.audioplaylist'),
        ),
        migrations.AddField(
            model_name='audioplaylistlink',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_uploads.audioplaylistlink_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='audioplaylist',
            name='av',
            field=models.ManyToManyField(through='uploads.AudioPlaylistLink', to='uploads.Audio'),
        ),
        migrations.AddField(
            model_name='audioplaylist',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_uploads.audioplaylist_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterUniqueTogether(
            name='audioplaylistlink',
            unique_together={('av', 'playlist')},
        ),
    ]
