# Generated by Django 3.2.9 on 2021-12-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0012_auto_20211207_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
