# Generated by Django 3.2.9 on 2021-12-03 20:10

from django.db import migrations, models
import django.db.models.deletion
import uploads.validators


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('uploads', '0013_auto_20211110_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('panopto_playlist_id', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AudioPlaylistLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['playlist_order'],
            },
        ),
        migrations.CreateModel(
            name='VideoPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('panopto_playlist_id', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoPlaylistLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_order', models.PositiveIntegerField(default=0)),
                ('av', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.video')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.videoplaylist')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_uploads.videoplaylistlink_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['playlist_order'],
                'unique_together': {('av', 'playlist')},
            },
        ),
        migrations.RemoveField(
            model_name='audiotrack',
            name='album',
        ),
        migrations.AlterModelOptions(
            name='upload',
            options={'permissions': [('view_inventory', 'Can view non-staff inventory of materials (for faculty)')], 'verbose_name_plural': 'Uploads (all types)'},
        ),
        migrations.AlterField(
            model_name='audio',
            name='upload',
            field=models.FileField(help_text='mp3, m4a or wav', max_length=1024, upload_to='av/audio/', validators=[uploads.validators.validate_audio]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='AudioAlbum',
        ),
        migrations.DeleteModel(
            name='AudioTrack',
        ),
        migrations.AddField(
            model_name='videoplaylist',
            name='av',
            field=models.ManyToManyField(through='uploads.VideoPlaylistLink', to='uploads.Video'),
        ),
        migrations.AddField(
            model_name='videoplaylist',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_uploads.videoplaylist_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='audioplaylistlink',
            name='av',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.audio'),
        ),
        migrations.AddField(
            model_name='audioplaylistlink',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.audioplaylist'),
        ),
        migrations.AddField(
            model_name='audioplaylistlink',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_uploads.audioplaylistlink_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='audioplaylist',
            name='av',
            field=models.ManyToManyField(through='uploads.AudioPlaylistLink', to='uploads.Audio'),
        ),
        migrations.AddField(
            model_name='audioplaylist',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_uploads.audioplaylist_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterUniqueTogether(
            name='audioplaylistlink',
            unique_together={('av', 'playlist')},
        ),
    ]
