# Generated by Django 3.2.9 on 2021-11-23 14:23

from django.db import migrations, models
import uploads.validators


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0014_auto_20211122_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='upload',
            field=models.FileField(help_text='mp3, m4a or wav', max_length=1024, upload_to='av/audio/', validators=[uploads.validators.validate_audio]),
        ),
    ]
