# Generated by Django 3.2.9 on 2021-11-23 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('uploads', '0015_alter_audio_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'permissions': [('view_inventory', 'Can view non-staff inventory of materials (for faculty)')], 'verbose_name_plural': 'Uploads (all types)'},
        ),
        migrations.RenameField(
            model_name='audioplaylist',
            old_name='audio',
            new_name='av',
        ),
        migrations.RenameField(
            model_name='audioplaylistlink',
            old_name='audio',
            new_name='av',
        ),
        migrations.RenameField(
            model_name='videoplaylist',
            old_name='video',
            new_name='av',
        ),
        migrations.RenameField(
            model_name='videoplaylistlink',
            old_name='video',
            new_name='av',
        ),
        migrations.AddField(
            model_name='audioplaylist',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_uploads.audioplaylist_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='audioplaylistlink',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_uploads.audioplaylistlink_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='videoplaylist',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_uploads.videoplaylist_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='videoplaylistlink',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_uploads.videoplaylistlink_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterUniqueTogether(
            name='audioplaylistlink',
            unique_together={('av', 'playlist')},
        ),
        migrations.AlterUniqueTogether(
            name='videoplaylistlink',
            unique_together={('av', 'playlist')},
        ),
    ]
