# Generated by Django 3.2.9 on 2021-12-17 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0016_auto_20211214_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioplaylistlink',
            name='av',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.audio', verbose_name='Audio – note that searching is case-sensitive!'),
        ),
        migrations.AlterField(
            model_name='videoplaylistlink',
            name='av',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.video', verbose_name='Video – note that searching is case-sensitive!'),
        ),
    ]
