# Generated by Django 3.2.9 on 2021-12-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0016_auto_20211123_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='title',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
