# Generated by Django 3.2.10 on 2022-01-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0017_auto_20211217_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioplaylist',
            name='description',
            field=models.TextField(blank=True, help_text='Publicly visible description, which may be copied to another service such as Panopto', null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='description',
            field=models.TextField(blank=True, help_text='Publicly visible description, which may be copied to another service such as Panopto', null=True),
        ),
        migrations.AddField(
            model_name='videoplaylist',
            name='description',
            field=models.TextField(blank=True, help_text='Publicly visible description, which may be copied to another service such as Panopto', null=True),
        ),
        migrations.AlterField(
            model_name='audioplaylist',
            name='notes',
            field=models.TextField(blank=True, help_text='Private notes for library staff', null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='notes',
            field=models.TextField(blank=True, help_text='Private notes for library staff', null=True),
        ),
        migrations.AlterField(
            model_name='videoplaylist',
            name='notes',
            field=models.TextField(blank=True, help_text='Private notes for library staff', null=True),
        ),
    ]
