# Generated by Django 3.2.10 on 2022-01-31 22:14
# Edited to add default Folder object

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

# Create new default Folder object as part of this migration
# https://docs.djangoproject.com/en/3.2/ref/migration-operations/#django.db.migrations.operations.RunPython
def forwards_func(apps, schema_editor):
    Folder = apps.get_model("uploads", "Folder")
    db_alias = schema_editor.connection.alias
    Folder.objects.create(
        id=settings.UPLOAD_FOLDER_PK,
        panopto_folder_id=settings.PANOPTO_FOLDER_ID,
        name='[Default upload folder]',
    )

def reverse_func(apps, schema_editor):
    Folder = apps.get_model("uploads", "Folder")
    db_alias = schema_editor.connection.alias
    Folder.objects.using(db_alias).get(id=settings.UPLOAD_FOLDER_PK).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0019_auto_20220127_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('panopto_folder_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RunPython(
            forwards_func,
            reverse_func,
        ),
        migrations.AddField(
            model_name='audio',
            name='folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='uploads.folder'),
        ),
        migrations.AddField(
            model_name='audioplaylist',
            name='folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='uploads.folder'),
        ),
        migrations.AddField(
            model_name='video',
            name='folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='uploads.folder'),
        ),
        migrations.AddField(
            model_name='videoplaylist',
            name='folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='uploads.folder'),
        ),
    ]
