# Generated by Django 3.2.10 on 2022-01-31 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0020_auto_20220131_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='notes',
            field=models.TextField(blank=True, help_text='Private notes for library staff', null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='panopto_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
