# Generated by Django 3.2.10 on 2022-02-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0021_auto_20220131_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(help_text='Will be overridden by Panopto folder name, if applicable', max_length=255, unique=True),
        ),
    ]
