# Generated by Django 3.2.12 on 2022-04-13 13:59

from django.db import migrations, models
import uploads.models
import uploads.validators


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0022_alter_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='upload',
            field=models.FileField(help_text='mp3, m4a or wav', max_length=1024, upload_to=uploads.models.get_upload_path, validators=[uploads.validators.validate_audio]),
        ),
        migrations.AlterField(
            model_name='text',
            name='upload',
            field=models.FileField(help_text='pdf format only', max_length=1024, upload_to=uploads.models.get_upload_path, validators=[uploads.validators.validate_text]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='form',
            field=models.CharField(choices=[('digitized', 'Digitized'), ('born_digital', 'Born Digital')], max_length=16),
        ),
        migrations.AlterField(
            model_name='video',
            name='upload',
            field=models.FileField(help_text='mp4 or mov format only', max_length=1024, upload_to=uploads.models.get_upload_path, validators=[uploads.validators.validate_video]),
        ),
        migrations.AlterField(
            model_name='vtttrack',
            name='upload',
            field=models.FileField(help_text='vtt format only', max_length=1024, upload_to=uploads.models.get_upload_path, validators=[uploads.validators.validate_captions]),
        ),
    ]
