# Generated by Django 3.2.13 on 2022-06-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0023_auto_20220413_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='panopto_session_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='delivery ID of Panopto session'),
        ),
        migrations.AlterField(
            model_name='video',
            name='panopto_session_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='delivery ID of Panopto session'),
        ),
    ]
