# Generated by Django 3.2.15 on 2024-11-23 15:04

from django.db import migrations, models
import uploads.models
import uploads.validators


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0024_auto_20220602_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='ereserves_record_url',
        ),
        migrations.AddField(
            model_name='upload',
            name='item_record_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Catalog record'),
        ),
        migrations.AlterField(
            model_name='video',
            name='upload',
            field=models.FileField(help_text='mp4 format preferred', max_length=1024, upload_to=uploads.models.get_upload_path, validators=[uploads.validators.validate_video]),
        ),
        migrations.AlterField(
            model_name='vtttrack',
            name='upload',
            field=models.FileField(help_text='vtt format preferred', max_length=1024, upload_to=uploads.models.get_upload_path, validators=[uploads.validators.validate_captions]),
        ),
    ]
